Snazzah/slash-create

lib/creator.js, src/creator.ts, test/creator.ts
This fixes a situation where one command out of many is updated and caused the other commands to disappear from Discord.
The root cause was that only the updated command is sent with a `PUT` requests and overwrites the commands resource completely, different from what a `PATCH` request does (modifies a resource).
https://en.wikipedia.org/wiki/Patch_verb#:~:text=The%20main%20difference%20between%20the,instructions%20to%20modify%20the%20resource.
=> Update commands fix

docs/general/faq.md, docs/index.yml, src/command.ts, src/constants.ts, src/context.ts, src/structures/resolvedMember.ts, src/util/multipartData.ts, src/util/requestHandler.ts
closes #31 
This allows attachments to be sent within messages. Note that attachments will not appear in **ephemeral messages** or **initial messages**.
```js
ctx.send({
content: 'hello',
file: [
{
name: 'a.txt',
file: Buffer.from('b')
},
{
name: 'b.txt',
file: Buffer.from('c')
}
]
});
```
```js
ctx.send({
content: 'hello',
file: {
name: 'a.txt',
file: Buffer.from('b')
}
});
```
=> feat: Send attachments

src/creator.ts
Before this PR, the `syncCommands` method would delete commands if `deleteCommands` is set to true, but only if the creator has at least one other command registered. This is because the method wouldn't send an empty payload.
This PR removes the empty payload check in `syncCommandsIn` and `syncCommandsGlobal` so it is allowed to be sent. An empty payload sent to the commands endpoint will delete all commands, as expected.
Guild commands still will not be deleted with `syncCommands` because the library has no way of knowing what guild commands exist without them being defined locally. But the user can still call `syncCommandsIn` directly with their guild ID(s) to delete all guild commands.
=> Allow empty payloads when syncing commands

src/constants.ts
Change type ApplicationCommandOption to give TypeScript warnings if the `options` field is set when `type` is not `SUB_COMMAND` or `SUB_COMMAND_GROUP`.
=> Change to ApplicationCommandOption

docs/general/faq.md
since it works sending an regular Embed or Embed (MessageEmbed) without using ".toJSON()", this warning should be edited.
=> fix square brackets and embed warning (docs)

docs/examples/components.md, src/constants.ts, src/index.ts, src/structures/interfaces/componentContext.ts, test/__util__/constants.ts, test/structures/interfaces/componentContext.ts
[Select Menu Component Documentation](https://discord.com/developers/docs/interactions/message-components#select-menus)
`ComponentActionRow#components` has been modified as per the spec of this component, which states:
> - An Action Row can only contain one select menu
> - An Action Row containing a select menu cannot also contain buttons
That said, I would expect changes to be suggested on this if this is considered as conflicting behaviour.
- Types `ComponentSelectMenu` and `ComponentSelectOption` are exported to the index
- `ComponentActionRow` now accepts `ComponentSelectMenu`
- Added `SELECT` to enum `ComponentType`
- Added `ComponentSelectMenu` as a component alternative of `AnyComponent`
- Added `values` property to `ComponentContext`
=> feat: Select Menu Component

src/constants.ts
A tiny change to make the description property in ComponentSelectOption optional.
The [API docs](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-option-structure) mention that it is optional, and I have been excluding it with `/** @ts-ignore */` just fine.
=> fix(types): make ComponentSelectOption.description optional

src/creator.ts, src/structures/interfaces/context.ts, src/structures/interfaces/messageInteraction.ts
=> Component callback rework

package.json
Very small PR. The project compiles just fine on Windows, but the bash "test" syntax makes it panic. Replacing it by [shx](https://github.com/shelljs/shx) via npx fixes this.
=> Allow compilation on Windows

src/constants.ts
From discord/discord-api-docs#3455
Only available from canary API and clients, should merge when stable.
closes #89
=> feat(types): add option type number

src/structures/interfaces/messageInteraction.ts
- Ensure `@original` message ref is set as `undefined` when calling `MessageInteractionContext#delete()`.
=> patch(MessageInteraction): remove message reference on delete

src/structures/channel.ts
Channel mentions don't work, as they shouldn't be using `@`.
=> Fix channel mentions

docs/examples/vercel.md, docs/index.yml, package.json, src/index.ts, src/servers/vercel.ts, yarn.lock
This adds a `VercelServer` class, which allows the bot to be hosted on [Vercel](https://vercel.com/) - a free hosting platform for serverless projects strongly integrated with Git.
A working code example is [available here](https://github.com/GabrielTK/VercelSlashCreate), is currently being hosted via Vercel and can be tested [with this invite link](https://discord.com/oauth2/authorize?client_id=619935227737014333&scope=bot%20applications.commands&permissions=8) (NOTE: The invite link by default includes Administrator permissions, but that should not change anything. If you feel uncomfortable with testing it this way, just change the `permissions` bit on the URL.
=> feat: Add Vercel Serverless Hosting Support

docs/examples/command.md, src/command.ts, src/constants.ts, src/creator.ts, src/index.ts, src/structures/interfaces/autocompleteContext.ts, test/__util__/constants.ts, test/structures/interfaces/autocompleteContext.ts
Adds [autocomplete stuff](https://devsnek.notion.site/devsnek/Application-Command-Option-Autocomplete-Interactions-dacc980320c948768cec5ae3a96a5886) to commands.
```ts
import { SlashCreator, SlashCommand, CommandOptionType, CommandContext, AutocompleteContext } from 'slash-create';
export default class ExampleCommand extends SlashCommand {
constructor(creator: SlashCreator) {
super(creator, {
name: 'example',
description: 'The.',
options: [
{
type: CommandOptionType.STRING,
name: 'astring',
description: '...',
autocomplete: true
}
]
});
}
async autocomplete(ctx: AutocompleteContext) {
// Get the focused option name with `ctx.focused`
// can use ctx.sendResults([{ name: 'A Title', value: 'a_value' }])
// or return an array of choices
return [{ name: `Your text: …
```
=> feat: Autocomplete options

src/constants.ts
- `ChannelType` enum
- `ApplicationCommandOptionChannel` extending from `...OptionBase`
- `ApplicationCommandOption` to include `ApplicationCommandOptionChannel` as part of the type union.
- `yarn.lock` had a removed a dependency for an eslint plugin
closes #142
=> Add channel type restriction option variant

src/constants.ts, test/__util__/constants.ts
The interaction received from Discord also includes an `application_id` field.
=> Missing property documentation

src/constants.ts, src/structures/interfaces/commandContext.ts, src/structures/role.ts
- `Role#icon` as a nullable string which is an image hash if available *including icons as uploaded from custom emojis*.
- `Role#unicode_emoji` as a nullable string which is... a unicode emoji.
- `get Role#iconURL` -> `Role#dynamicIconURL()`
- `Role#dynamicIconURL(format?, size?)` which returns as `null` if `#icon` doesn't exist.
- `ROLE_ICON(format, size)` cdn route to Endpoints
*`Role#icon` and `Role#unicode_emoji` are reflected from `ResolvedRole` as it's sibling type definition.*
=> Add role icon properties to ResolvedRole

src/constants.ts
Adds the `min_value` and `max_value` properties to the `CommandIntegerOption` interface
closes #174
=> Add `min_value` and `max_value` types to integer/number options

src/constants.ts, src/structures/interfaces/autocompleteContext.ts, src/structures/interfaces/commandContext.ts, src/structures/interfaces/messageInteraction.ts, src/structures/member.ts, src/structures/resolvedMember.ts
- `ResolvedMember#avatarURL()`
- `ResolvedMember#dynamicAvatarURL(format?: ImageFormat, size?: number)`
- `ResolvedMemberData.avatar?`
---
- `ResolvedMember` and `Member` (as child of the former) now take a `guildID` argument **after** the `creator` argument.
> Existence of `guildID` is guaranteed if `Member` or `ResolvedMember` is instantiated.
* `ResolvedMember#id` *can* also be converted into a getter since it's from `userData`.
* `ResolvedMember#is_pending` is not a property of the [GuildMember](https://discord.dev/docs/resources/guild#guild-member-object) structure (partial or not).
=> feat: Add member avatar endpoint with related methods

src/creator.ts, src/structures/interfaces/messageInteraction.ts
This extends further from #145 by adding a listener for all components on a message as a wildcard - the component used can be determined by [`ctx.custom_id`](https://slash-create.js.org/#/docs/main/latest/class/ComponentContext?scrollTo=customID).
- `MessageInteractionContext#registerWildcardComponent(message_id, callback, expiration, onExpired)`
- `MessageInteractionContext#unregisterWildcardComponent(message_id)`
*Wildcard components use the invoking message ID with an asterisk (`*`) to prevent possible conflicts with existing registered components.*
For context sake, this was implemented with eda121e ([Gist Component](https://gist.github.com/sudojunior/e720cc1083c08d1258e9835d692b49b1)) with a specific use for ephemeral components (and having it unregister itself immediately before …
=> feat: add wildcard components

package.json
- Prior to the implimentation of Node v16 package requirement
- Loss of access to `reverse`, `ensure` (`0.4.x`)
- Loss of access to `at` and `keyAt` (`0.3.x`)
Last available release at 27th October 2021.
Full diff changeset: https://github.com/discordjs/collection/compare/v0.2.1...v0.4.0
=> patch(dep): Force usage of `djs/collection@0.2.4`

src/creator.ts
When this library still used `require-all`, it was possible to load TS files during dev with
```ts
.registerCommandsIn({
filter: /^([^.].*)\.(?:js|ts)$/,
dirname: join(__dirname, 'commands'),
})
```
This is no longer possible since 5.x, so this PR aims at supporting it out-of-the-box.
=> Support registering custom file extensions

src/structures/interfaces/modalInteractionContext.ts
* method cloned from `ComponentContext`
possibility was suggested by @mount2010 for skipping deferral
=> feat: allow ack for `ModalInteractionContext`

src/constants.ts, src/structures/interfaces/modalInteractionContext.ts
* `ModalInteractionContext` - both new members are akin to the close relative of `ComponentContext`
* Added `#data`
> Allowing possible workarounds for any new additions Discord makes if the library is not updated in time.
* Added `#message` for modal contexts that originate from a Message Component.
* Added `#editParent(content, options)`
> This will check for existence from the payload before attempting to patch the message itself.
It has been noted that this kind of contribution is discouraged with how the library is structured, and beginning to see code repeated across it's interfaces. The possibility of having a `BaseInteractionContext` class to have all _contexts_ derive from was a future alternative that was discussed to contain the core elements of any *non-ping* interaction …
=> feat: Add `#editParent` and `#data` to `ModalInteractionContext`

docs/examples/command.md, src/command.ts, src/constants.ts, src/creator.ts
From https://github.com/discord/discord-api-docs/pull/4653
Will test later, *might* have a way to asynchronously get localizations for potential integrations with i18next with some async function named `onLoad`.
=> feat: add command localizations

src/api.ts, src/creator.ts, src/server.ts, src/servers/azure.ts, src/servers/express.ts, src/servers/fastify.ts, src/servers/gcf.ts, src/servers/lambda.ts, src/servers/vercel.ts, src/structures/interfaces/componentContext.ts, src/structures/interfaces/messageInteraction.ts, src/structures/interfaces/modalInteractionContext.ts
Allow for initial messages to have attachments.
Servers to support:
- Cloudflare Workers (in seperate repo)
=> feat: initial response attachments support

docs/examples/command.md, src/api.ts, src/command.ts, src/constants.ts, src/creator.ts, src/structures/permissions.ts, test/__util__/commands.ts, test/__util__/nock.ts, test/creator.ts
https://github.com/discord/discord-api-docs/pull/4830
=> refactor: Permissions V2 Rework

src/util/lambdaHeaders.ts, test/util/lambdaHeaders.ts
Since the other servers use lowercase headers, might as well have AWS normalize headers aswell.
@cernec1999 Can you make sure this works for you? This will supercede #307.
=> fix(util): change headers to be lowercase in lambda headers

src/structures/message.ts
Current interfaces are missing properties from what is present via https://discord.com/developers/docs/resources/channel#embed-object-embed-structure
=> fix(types): fix Embed types

src/structures/interfaces/messageInteraction.ts, src/util.ts, src/util/requestHandler.ts, test/structures/interfaces/messageInteraction.ts
* remains to be fully tested, and documented
* initial tests reveal attachments may need to retain original attachment IDs from the sent message
* specifying `attachments` as part of the message body, removes the ability to auto resolve attachment indexes
<details>
<summary>Possible command for deployment test</summary>
```ts
import { CommandContext, SlashCommand, SlashCreator } from 'slash-create';
export default class FileTestCommand extends SlashCommand {
constructor(creator: SlashCreator) {
super(creator, {
name: 'file-test',
description: 'Test file upload'
});
}
async run(ctx: CommandContext) {
await ctx.defer();
await ctx.send({
content: "Here's a file!",
file: {
name: 'test.txt',
file: Buffer.from('This is a test file.')
}
});
await ctx.editOriginal({
content: "Here's another …
```
=> patch: modify multipart logic to support attachment IDs / indexes

src/servers/azure.ts, src/servers/express.ts, src/servers/fastify.ts, src/servers/gcf.ts, src/servers/lambda.ts, src/servers/vercel.ts
Carries over from #358 to correct `400: Invalid Form Error` on initial response.
This could have been done one of three ways:
```ts
for (const i in response.files) data.attach(`files[${i}]`, response.files[i].file, response.file[i].name); // 1 **
for (const [i, file] in response.files.entries()) data.attach(`files[${i}]`, file.file, file.name); // 2
// ---
let index = 0;
for (const file of response.files) data.attach(`files[${index++}]`, file.file, file.name); // 3
```
=> patch: reflect changes from #358 onto server responses

docs/examples/components.md, src/creator.ts
added method SlashCreator#registerGlobalModal 
added method SlashCreator#unregisterGlobalModal
modified method SlashCreator#_onInteraction to search using global callback key
example created for global modal under docs/examples/components.md
=> feat: register global modals

src/constants.ts
Took me a few to figure out why the `channel_types` command option wasn't including forums.
See [Channel Types](https://discord.com/developers/docs/resources/channel#channel-object-channel-types).
=> fix: fix GUILD_FORUM enum value

src/creator.ts, src/util/requestHandler.ts
This patch opens up some private methods, specifically: RequestHandler._creator
Creator._onRequest
Creator._onInteraction
This patch is required for the CF worker to be typesafe.
=> chore: Changes access control on key internal methods.

src/structures/resolvedMember.ts
The interactions dispatches an additional field `flags` in executing- and resolved members. This pull requests simply adds this fields to the `ResolvedMember` class.
=> feat(member): Add `flags` property

src/structures/user.ts
As documented under [Image Formatting](https://discord.com/developers/docs/reference#image-formatting), users on the new username system can use the previously unused sixth default avatar. This PR corrects `User#defaultAvatar` to account for this.
=> fix(user): correct default avatar index

src/structures/message.ts
Seems like during the development of the latest update (User-Installable Apps) the debug logging was not removed before the release. This now spams the console with every interaction and should be removed again.
=> Removed debug logging

src/structures/channel.ts
The permissions field of the channel contains the permissions of the invoking user in the channel and not of the application.
See https://discord.com/developers/docs/resources/channel#channel-object-channel-structure
=> chore: update permissions description

src/index.ts
I am using a somewhat modified version of Slash-Create to support multi-token bots. To avoid extra maintenance I simply leverage JS to modify methods, specifically, the `_onRequest` handler.
I bring my own slightly modified version of the method in a dedicated file and override the method and binds. However, this request handler method depends on the `verifyKey` utility.
It would be nice if it was also exported so I could simply import via something like this
```ts
// In my onRequest.ts
import { verifyKey } from "slash-create";
// ... rest of the _onRequest() handler, with modifications
```
=> feat: export utils

src/constants.ts
- Added missing ButtonStyle (https://github.com/Snazzah/slash-create/commit/780f64afda75ef3269925da2b7d00a00634d9705)
- Made label optional according to [Button Structure](https://discord.com/developers/docs/interactions/message-components#button-object-button-structure)
=> feat(constants): Updated ComponentButton

src/constants.ts, src/structures/interfaces/messageInteraction.ts
- Added new premium button style
- Marked `PREMIUM_REQUIRED (10)` interaction response type as deprecated
Refs:
- https://github.com/discord/discord-api-docs/pull/6875
- https://discord.com/developers/docs/change-log#premium-apps-new-premium-button-style-deep-linking-url-schemes
=> feat: added premium button

.eslintrc.js, pnpm-lock.yaml, src/creator.ts, src/server.ts, src/servers/cfworker.ts, src/structures/interfaces/autocompleteContext.ts, src/structures/interfaces/baseInteraction.ts, src/structures/interfaces/commandContext.ts, src/structures/interfaces/componentContext.ts, src/structures/interfaces/messageInteraction.ts, src/structures/interfaces/modalInteractionContext.ts, src/structures/interfaces/modalSendableContext.ts
This is a straightforward solution to #620, implementing a `CommandContext.serverContext` property that can be defined by the Server.
`CommandContext.serverContext` is naturally a generic of the default type `unknown`, leaving the user responsible for determining its type and handling casts accordingly. This fits with the use case of CloudFlare Workers, as its structure changes depending on how bindings are defined.
Consequently, this PR enables using Durable Objects and D1 databases in bots. Through the use of [Durable Objects](https://developers.cloudflare.com/durable-objects/), many things that could only previously be achieved in stateful workflows can now be achieved in serverless.
=> feat(server): Add Server Context Support

src/creator.ts
A typo caused slash-create to throw internal errors if a modal was submitted and a global modal submit handler was registered - The code checks whether `globalCallbackKey` exists in `_modalCallbacks`, but then tries to access `modalCallbackKey` in `_modalCallbacks`.
Fixing the typo allows developers to use `creator.registerGlobalModal` again.
=> fix(user): global modal submit handlers causing internal errors

src/constants.ts
It's still on development, but discord.js already has it. Would be nice to have it in slash-create too. More info on [https://discord.com/developers/docs/resources/channel#channel-object-channel-types](https://discord.com/developers/docs/resources/channel#channel-object-channel-types)
=> feat(constants): Added GUILD_MEDIA channel type

src/command.ts
The regex was updated in https://github.com/Snazzah/slash-create/commit/9832a860baaf4a075383754d6c18a05fdcc6d0c4, but the error message was not
=> Fixed command name RangeError message

src/creator.ts
Modal callbacks aren't being awaited for some reason, leading to early execution pauses for Cloudflare workers.
Fixes #630
=> fix(creator): await modal callbacks

src/constants.ts
`options` is not available for Channel Selects
=> chore(types): improve on select types
